### ISSUE TITLE
Retour DeMemoire

### ISSUE THREAD

**Issue by nivetml** [Vietco311/L3#3]
C'est la méthode lancer() sans paramètre qu'il fallait redéfinir en assurant par la sauvegarde de la dernière valeur de dé sortie que le lancer ne puisse pas générer deux fois à suivre la même valeur... A revoir.

Ce System.err.println n'était pas demandé dans l'énoncé ! Le dé est seulement ne pas être sensé renvoyer deux fois la même valeur à suivre... 
https://github.com/Vietco311/L3/blob/b1c0851ad5b68b15b440b03648e773855f0f76d1/Java%20POO/TP1/src/exercice1/De_memoire.java#L20

**Comment by Vietco311** [comment]
Bonjour Madame, tout est pris en note, je rectifie tout ça dès que
possible. En revanche j’avoue ne pas comprendre comment interdire une
valeur d’un lancer non consécutif, par deux appellent différents de
lancer().

**Comment by Vietco311** [comment]
Non c’est bon, je viens de comprendre, désolé du dérangement.

Le lun. 26 sept. 2022 à 17:01, Anthony Colin ***@***.***> a
écrit :
