### ISSUE TITLE
Des.java Leculier Lucas

### ISSUE THREAD

**Issue by LucasLeculier** [Vietco311/L3#4]
Il faudrait ajouter une constante NBFACESDEFAUT qui pourra empêcher d'avoir this.nbFace=6 ; (L57) et les initialisations a 6 dans les constructeurs (dans le cas ou le nombre de dés par default il faudra donc ici changer les valeurs dans les constructeurs et sur la ligne 57 au lieu de juste changer la valeur passée en constante dans la déclaration) 

https://github.com/Vietco311/L3/blob/main/Java%20POO/TP1/src/exercice1/Des.java#L4

protected static int nbDes=0; aide a avoir une meilleure visibilité.

https://github.com/Vietco311/L3/blob/main/Java%20POO/TP1/src/exercice1/Des.java#L10

La fonction peut être remplacée par : return r.nextInt(nbFaces + 1);

https://github.com/Vietco311/L3/blob/main/Java%20POO/TP1/src/exercice1/Des.java#L68

Une condition if nbAleatoire == MAX { return nbAleatoire;}
Pour que la boucle s'arrête lorsque le nombre tiré est le nombre maximum ( aucun lancer ne pourra battre ce dernier)  et empêche donc que la boucle aille au bout dans le cas ou le nombre de lancer passé en paramètre est très grand (le lancer se fait entre 1 et 120 donc dans le cas d'un nombre de lancer très important on trouvera forcément le max avant la fin de la boucle for                           

https://github.com/Vietco311/L3/blob/main/Java%20POO/TP1/src/exercice1/Des.java#L74

**Comment by Vietco311** [comment]
Je suis passé sur un while au lieu d'un if puis return pour éviter de d'avoir plusieurs return dans la méthode.
