### ISSUE TITLE
Code Review pour la classe Des.java

### ISSUE THREAD

**Issue by tbmutisma** [Vietco311/L3#5]
Faire une documentation avec des commentaires multilignes avec parametres et type de retour, voir [https://www.oracle.com/fr/technical-resources/articles/java/javadoc-tool.html#format](url) pour le format
https://github.com/Vietco311/L3/blob/5283e30b4758627de88c6d4a9c547067eb7b247e/Java%20POO/TP1/src/exercice1/Des.java#L15

Accéder à l'attribut directement avec `nbFaces = nNbFaces` plutot que d'utiliser le Setter
https://github.com/Vietco311/L3/blob/5283e30b4758627de88c6d4a9c547067eb7b247e/Java%20POO/TP1/src/exercice1/Des.java#L24

Utiliser une convention camelCase ici plutot que du snake_case pour le nom de la méthode set de nbDes
https://github.com/Vietco311/L3/blob/5283e30b4758627de88c6d4a9c547067eb7b247e/Java%20POO/TP1/src/exercice1/Des.java#L46

Utiliser la méthode Format() de la classe String plutot que de concaténer 
https://github.com/Vietco311/L3/blob/5283e30b4758627de88c6d4a9c547067eb7b247e/Java%20POO/TP1/src/exercice1/Des.java#L87

**Comment by Vietco311** [comment]
Fait la plupart mais je garde le setter(Comme ça m'avait été recommandé par la prof pour éviter la duplication) et le toString parce que j'avoue ne pas comprendre comment marche format()
